services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
  cadence:
    image: ubercadence/server:master-auto-setup
    ports:
    - FRONTEND_PORT:7933
    - FRONTEND_PORT_GRPC:7833
    environment:
      - "DB=mysql"
      - "MYSQL_USER=root"
      - "MYSQL_PWD=root"
      - "MYSQL_SEEDS=mysql"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
    - mysql
  cadence-web:
    image: ubercadence/web:latest
    environment:
      - "CADENCE_GRPC_PEERS=cadence:7833"
    ports:
      - "8088:8088"
    depends_on:
      - cadence
